# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, constr


class OlfEnvelope(BaseModel):
    id: UUID
    type: constr(pattern=r'^([a-z][a-z0-9_]*|x(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?){2,})$')
    olf_version: constr(pattern=r'^[0-9]+\.[0-9]+$')
    occurred_at: AwareDatetime
    recorded_at: AwareDatetime
    tz: constr(min_length=1) | None = None
    source: constr(pattern=r'^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')
    payload: dict[str, Any]
