# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, constr


class InputMethod(Enum):
    photo = 'photo'
    text = 'text'
    manual = 'manual'


class MealItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    grams: confloat(ge=0.0) | None = None
    kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None


class OlfMealPayload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0)
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0)
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0)
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0)
    items: list[MealItem] | None = None


class OlfMealPayload6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] = Field(..., min_length=1)


class OlfMealPayload(
    RootModel[
        OlfMealPayload1
        | OlfMealPayload2
        | OlfMealPayload3
        | OlfMealPayload4
        | OlfMealPayload5
        | OlfMealPayload6
    ]
):
    root: (
        OlfMealPayload1
        | OlfMealPayload2
        | OlfMealPayload3
        | OlfMealPayload4
        | OlfMealPayload5
        | OlfMealPayload6
    ) = Field(..., title='OLF meal payload')
