# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class InputMethod(Enum):
    photo = 'photo'
    text = 'text'
    manual = 'manual'


class MealItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(min_length=1)]
    grams: Annotated[float | None, Field(ge=0.0)] = None
    kcal: Annotated[float | None, Field(ge=0.0)] = None
    protein_g: Annotated[float | None, Field(ge=0.0)] = None
    fat_g: Annotated[float | None, Field(ge=0.0)] = None
    carbs_g: Annotated[float | None, Field(ge=0.0)] = None


class OlfMealPayload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str
    note: str | None = None
    total_kcal: Annotated[float | None, Field(ge=0.0)] = None
    protein_g: Annotated[float | None, Field(ge=0.0)] = None
    fat_g: Annotated[float | None, Field(ge=0.0)] = None
    carbs_g: Annotated[float | None, Field(ge=0.0)] = None
    items: list[MealItem] | None = None


class OlfMealPayload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: Annotated[float, Field(ge=0.0)]
    protein_g: Annotated[float | None, Field(ge=0.0)] = None
    fat_g: Annotated[float | None, Field(ge=0.0)] = None
    carbs_g: Annotated[float | None, Field(ge=0.0)] = None
    items: list[MealItem] | None = None


class OlfMealPayload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: Annotated[float | None, Field(ge=0.0)] = None
    protein_g: Annotated[float, Field(ge=0.0)]
    fat_g: Annotated[float | None, Field(ge=0.0)] = None
    carbs_g: Annotated[float | None, Field(ge=0.0)] = None
    items: list[MealItem] | None = None


class OlfMealPayload4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: Annotated[float | None, Field(ge=0.0)] = None
    protein_g: Annotated[float | None, Field(ge=0.0)] = None
    fat_g: Annotated[float, Field(ge=0.0)]
    carbs_g: Annotated[float | None, Field(ge=0.0)] = None
    items: list[MealItem] | None = None


class OlfMealPayload5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: Annotated[float | None, Field(ge=0.0)] = None
    protein_g: Annotated[float | None, Field(ge=0.0)] = None
    fat_g: Annotated[float | None, Field(ge=0.0)] = None
    carbs_g: Annotated[float, Field(ge=0.0)]
    items: list[MealItem] | None = None


class OlfMealPayload6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: Annotated[float | None, Field(ge=0.0)] = None
    protein_g: Annotated[float | None, Field(ge=0.0)] = None
    fat_g: Annotated[float | None, Field(ge=0.0)] = None
    carbs_g: Annotated[float | None, Field(ge=0.0)] = None
    items: Annotated[list[MealItem], Field(min_length=1)]


class OlfMealPayload(
    RootModel[
        OlfMealPayload1
        | OlfMealPayload2
        | OlfMealPayload3
        | OlfMealPayload4
        | OlfMealPayload5
        | OlfMealPayload6
    ]
):
    root: Annotated[
        OlfMealPayload1
        | OlfMealPayload2
        | OlfMealPayload3
        | OlfMealPayload4
        | OlfMealPayload5
        | OlfMealPayload6,
        Field(title='OLF meal payload'),
    ]
