# GENERATED by mise run gen:py — do not edit by hand.
# Source: schemas/*/1.json



from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, constr


class OlfEnvelope(BaseModel):
    id: UUID
    type: constr(pattern=r'^([a-z][a-z0-9_]*|x(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?){2,})$')
    olf_version: constr(pattern=r'^[0-9]+\.[0-9]+$')
    occurred_at: AwareDatetime
    recorded_at: AwareDatetime
    tz: constr(min_length=1) | None = None
    source: constr(pattern=r'^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')
    payload: dict[str, Any]


from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, constr


class InputMethod(Enum):
    photo = 'photo'
    text = 'text'
    manual = 'manual'


class MealItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    grams: confloat(ge=0.0) | None = None
    kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None


class OlfMealPayload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0)
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0)
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0)
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] | None = None


class OlfMealPayload5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0)
    items: list[MealItem] | None = None


class OlfMealPayload6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_method: InputMethod | None = None
    source_ref: str | None = None
    raw_input: str | None = None
    note: str | None = None
    total_kcal: confloat(ge=0.0) | None = None
    protein_g: confloat(ge=0.0) | None = None
    fat_g: confloat(ge=0.0) | None = None
    carbs_g: confloat(ge=0.0) | None = None
    items: list[MealItem] = Field(..., min_length=1)


class OlfMealPayload(
    RootModel[
        OlfMealPayload1
        | OlfMealPayload2
        | OlfMealPayload3
        | OlfMealPayload4
        | OlfMealPayload5
        | OlfMealPayload6
    ]
):
    root: (
        OlfMealPayload1
        | OlfMealPayload2
        | OlfMealPayload3
        | OlfMealPayload4
        | OlfMealPayload5
        | OlfMealPayload6
    ) = Field(..., title='OLF meal payload')


from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Stage(Enum):
    in_bed = 'in_bed'
    core = 'core'
    deep = 'deep'
    rem = 'rem'
    awake = 'awake'
    asleep = 'asleep'
    unknown = 'unknown'


class SleepStage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage
    started_at: AwareDatetime
    ended_at: AwareDatetime


class OlfSleepPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ended_at: AwareDatetime
    stages: list[SleepStage] | None = None


from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class OlfStepsPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: conint(ge=0)
    ended_at: AwareDatetime


from pydantic import BaseModel, ConfigDict, PositiveFloat, confloat


class OlfWeightPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weight_kg: PositiveFloat
    body_fat_percent: confloat(ge=0.0, le=100.0) | None = None
    note: str | None = None
