# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Stage(Enum):
    in_bed = 'in_bed'
    core = 'core'
    deep = 'deep'
    rem = 'rem'
    awake = 'awake'
    asleep = 'asleep'
    unknown = 'unknown'


class SleepStage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage
    started_at: AwareDatetime
    ended_at: AwareDatetime


class OlfSleepPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ended_at: AwareDatetime
    stages: list[SleepStage] | None = None
