# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class OlfStepsPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: Annotated[int, Field(ge=0)]
    ended_at: AwareDatetime
