# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class OlfStepsPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: conint(ge=0)
    ended_at: AwareDatetime
