# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, PositiveFloat, confloat


class OlfWeightPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weight_kg: PositiveFloat
    body_fat_percent: confloat(ge=0.0, le=100.0) | None = None
    note: str | None = None
