# generated by datamodel-codegen:
#   filename:  1.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class OlfWeightPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weight_kg: Annotated[float, Field(gt=0.0)]
    body_fat_percent: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    note: str | None = None
