// GENERATED by scripts/gen_ts.mjs — do not edit by hand.

export interface OLFEnvelope {
  id: string;
  type: string;
  olf_version: string;
  occurred_at: string;
  recorded_at: string;
  tz?: string;
  source: string;
  payload: {};
}

export type OLFMealPayload = (
  | {
      [k: string]: unknown;
    }
  | {
      items: {
        [k: string]: unknown;
      };
    }
) & {
  input_method?: "photo" | "text" | "manual";
  source_ref?: string;
  raw_input?: string;
  note?: string;
  total_kcal?: number;
  protein_g?: number;
  fat_g?: number;
  carbs_g?: number;
  items?: MealItem[];
};

export interface MealItem {
  name: string;
  grams?: number;
  kcal?: number;
  protein_g?: number;
  fat_g?: number;
  carbs_g?: number;
}

export interface OLFSleepPayload {
  ended_at: string;
  stages?: SleepStage[];
}
export interface SleepStage {
  stage: "in_bed" | "core" | "deep" | "rem" | "awake" | "asleep" | "unknown";
  started_at: string;
  ended_at: string;
}

export interface OLFStepsPayload {
  count: number;
  ended_at: string;
}

export interface OLFWeightPayload {
  weight_kg: number;
  body_fat_percent?: number;
  note?: string;
}

