import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { compile } from "json-schema-to-typescript";

const SCHEMAS = "schemas";
const OUT = "bindings/typescript/olf.ts";

const types = (await readdir(SCHEMAS, { withFileTypes: true }))
	.filter((d) => d.isDirectory())
	.map((d) => d.name)
	.sort();

let out = "// GENERATED by scripts/gen_ts.mjs — do not edit by hand.\n\n";
for (const type of types) {
	const schema = JSON.parse(
		await readFile(join(SCHEMAS, type, "1.json"), "utf8"),
	);
	const ts = await compile(schema, schema.title ?? type, {
		bannerComment: "",
		additionalProperties: false,
	});
	out += `${ts}\n`;
}
await mkdir("bindings/typescript", { recursive: true });
await writeFile(OUT, out);
console.log(`wrote ${OUT} for: ${types.join(", ")}`);
